# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run build --if-present
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myreact
        # A file, directory or wildcard pattern that describes what to upload
        path: build
      
          - uses: actions/download-artifact@master
    - name: Build Docker container1
      run: docker build -t prasanna002/prasannasanthosh .
    - run: docker login -u prasanna002 -p Muthala@123P
    - run: docker push prasanna002/prasannasanthosh
